# Generated by Django 4.0.2 on 2022-02-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('about', models.CharField(max_length=300, verbose_name='About')),
                ('stars', models.IntegerField()),
                ('watching', models.IntegerField()),
                ('forks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('name', models.CharField(max_length=255, verbose_name='First and Last name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('repositories', models.ManyToManyField(to='users.Repository')),
            ],
        ),
    ]
