# Generated by Django 4.0.2 on 2022-02-06 18:14

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(nickname="Admin",
         password="admin",
         name="Ivan Gavrilov",
         email="test@test.com",
         phone="test")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
        